/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela_principal;

import analisador_lexico.Token;
import java.io.StringReader;

/**
 *
 * @author Regina
 */
public class LexicoSintatico extends javax.swing.JFrame {

    
    /**
     * Creates new form LexicoSintatico
     */
    public LexicoSintatico() {
        initComponents();
        txtSaidaLexico.setEditable(false);
        txtSaidaSintatico.setEditable(false);
    }
    
    
      
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSaidaSintatico = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtSaidaLexico = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jButtonLexico = new javax.swing.JButton();
        jButtonSintatico = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonAnalisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Swis721 Blk BT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Analisador Sintático");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(480, 320, 320, 20);

        txtSaidaSintatico.setColumns(20);
        txtSaidaSintatico.setRows(5);
        jScrollPane3.setViewportView(txtSaidaSintatico);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(440, 350, 350, 280);

        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);
        jScrollPane5.setViewportView(txtEntrada);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(30, 80, 760, 200);

        jLabel9.setFont(new java.awt.Font("Swis721 Blk BT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PROGRAMOL");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 40, 320, 20);

        txtSaidaLexico.setColumns(20);
        txtSaidaLexico.setRows(5);
        jScrollPane6.setViewportView(txtSaidaLexico);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(30, 350, 350, 280);

        jLabel10.setFont(new java.awt.Font("Swis721 Blk BT", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Analisador Léxico");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 320, 320, 20);

        jButtonLexico.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLexico.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jButtonLexico.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLexico.setText("Analisar Léxico");
        jButtonLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLexicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLexico);
        jButtonLexico.setBounds(830, 260, 280, 60);

        jButtonSintatico.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSintatico.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jButtonSintatico.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSintatico.setText("Analisar Sintático");
        jButtonSintatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSintaticoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSintatico);
        jButtonSintatico.setBounds(830, 360, 280, 60);

        jButtonLimpar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLimpar.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jButtonLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(830, 460, 280, 60);

        jButtonAnalisar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAnalisar.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jButtonAnalisar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAnalisar.setText("Léxico + Sintático");
        jButtonAnalisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnalisar);
        jButtonAnalisar.setBounds(830, 160, 280, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela_principal/cb8e41a8a534de21fb11dc70a383e3cc.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1120, 660);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(30, 220, 610, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela_principal/cb8e41a8a534de21fb11dc70a383e3cc.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 890, 940);

        setSize(new java.awt.Dimension(1139, 683));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
     
   
        
       
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLexicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLexicoActionPerformed

    private void jButtonSintaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSintaticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSintaticoActionPerformed

    private void jButtonAnalisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnalisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LexicoSintatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LexicoSintatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LexicoSintatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LexicoSintatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LexicoSintatico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnalisar;
    private javax.swing.JButton jButtonLexico;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSintatico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextArea txtEntrada;
    private javax.swing.JTextArea txtSaidaLexico;
    private javax.swing.JTextArea txtSaidaSintatico;
    // End of variables declaration//GEN-END:variables
}
