
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisador_sintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINHA = 15;
  public static final int CHAVE_FIM = 11;
  public static final int RESERVADO_FIM = 26;
  public static final int CHAVE_INICIO = 10;
  public static final int FIM_COMANDO = 17;
  public static final int OPERADOR_RELACIONAL = 7;
  public static final int FIM_LINHA = 21;
  public static final int ERROR = 16;
  public static final int ID = 2;
  public static final int TIPO = 28;
  public static final int NUMEROS_NATURAIS = 4;
  public static final int ATRIBUICAO = 12;
  public static final int PARENTESES_FIM = 24;
  public static final int EOF = 0;
  public static final int OPERADOR_ARITMETICO = 3;
  public static final int OPERADOR_ATRIBUICAO = 9;
  public static final int RESERVADO_ELSE = 19;
  public static final int PARENTESES_INICIO = 23;
  public static final int RESERVADO_THEN = 13;
  public static final int TEXTO = 5;
  public static final int RESERVADO_WHILE = 20;
  public static final int error = 1;
  public static final int INICIO_COMANDO = 22;
  public static final int OPERADOR_LOGICO = 6;
  public static final int RESERVADO_IF = 14;
  public static final int TIPO_NUMERICO = 27;
  public static final int NUMEROS_REAIS = 8;
  public static final int RESERVADO_INICIO = 25;
  public static final int BRANCO = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "OPERADOR_ARITMETICO",
  "NUMEROS_NATURAIS",
  "TEXTO",
  "OPERADOR_LOGICO",
  "OPERADOR_RELACIONAL",
  "NUMEROS_REAIS",
  "OPERADOR_ATRIBUICAO",
  "CHAVE_INICIO",
  "CHAVE_FIM",
  "ATRIBUICAO",
  "RESERVADO_THEN",
  "RESERVADO_IF",
  "LINHA",
  "ERROR",
  "FIM_COMANDO",
  "BRANCO",
  "RESERVADO_ELSE",
  "RESERVADO_WHILE",
  "FIM_LINHA",
  "INICIO_COMANDO",
  "PARENTESES_INICIO",
  "PARENTESES_FIM",
  "RESERVADO_INICIO",
  "RESERVADO_FIM",
  "TIPO_NUMERICO",
  "TIPO"
  };
}

